### ISSUE TITLE
10.13.6升级10.14.4出现问题

### ISSUE THREAD

**Issue by dakkidaze** [ourfor/Mibook-air#10]
从App Store升级的，问题具体表现为：
下载完更新，按照程序的提示第一次重启后，在Clover中可以看到安装的启动项，加入启动参数 -v之后，观察启动状况，发现到最后出现`Attempting System Restart... `后重启（此时滚屏速度相当快，很多细节都看不清），多次尝试均出现此情况，第二次之后会出现`This system was rebooted from panic`
机型为7500U指纹版

**Comment by saltpi** [comment]
这两个版本差太大了，你升级的时候使用的是最新的efi吗？

**Comment by dakkidaze** [comment]
从Release下载的，我先前试过用这个EFI直接引导10.14.4镜像的时候也出现过相同的问题，才装了10.13.6

**Comment by saltpi** [comment]
我建议你下载10.14.4的完整镜像，比如黑果小兵的，然后用这个efi应该，这样应该是没问题的

**Comment by dakkidaze** [comment]
感谢，我先试一试

**Comment by dakkidaze** [comment]
出现了诡异的现象
用黑果小兵10.14.4的镜像自带的EFI是可以引导安装程序进入准备安装界面的，
但是这个EFI就不行

**Comment by saltpi** [comment]
嗯，是有这样的情况，安装的时候用小兵的，安装完后再替换

**Comment by dakkidaze** [comment]
不行，用小兵的成功引导了Mojave升级程序以后无法用Release的EFI引导升级完成的10.14.4
症状一样，Panic

**Comment by dakkidaze** [comment]
全新安装10.14.4也是同样的结果，无法引导

**Comment by saltpi** [comment]
你BIOS版本和我的一样吗？

**Comment by dakkidaze** [comment]
版本是一样的，但是我用小兵的EFI引导了系统，然后把release里的EFI中的config.plist和全部的kext都拿了过来，现在能引导10.14.4了

唯一的问题就是每次开机都提示kernel panic，系统启动后提示出现问题而重启，但是并不影响使用

EDIT:具体步骤是

 安装完10.14.4之后，先用小兵的EFI引导进入系统，然后将小兵的EFI拷到EFI分区下，删除config.plist和kexts文件夹，然后用Release的EFI中的对应文件（夹）替换

达到的效果就是每次开机都五国，登录后后提示出现问题而重启，但并不影响使用

**Comment by saltpi** [comment]
这个你开机的时候按f11清除nvram可以清除这个登录后的提示，你这情况我看着有点像dsdt的原因，你可以删掉acpi里面的patched文件夹里面的东西看看

**Comment by dakkidaze** [comment]
这次重装清除nvram以后似乎正常了，也没有删acpi里的东西，里面的东西好像是屏蔽独显用的就没动

另外这个触控板驱动还是有问题，安装的时候就没法用，装完了还是没法用，之前几次安装的时候还是能用的

**Comment by saltpi** [comment]
触控板应该是没问题的，你看看你删了触控板驱动没有，另外有个键盘的驱动不能和触控板驱动共存，你看看你是不是添加了额外的驱动` VoodooPS2Controller  `

**Comment by dakkidaze** [comment]
kexts里只有`ApplePS2SmartTouchPad.kext`，没有`VoodooPS2Controller`

**Comment by dakkidaze** [comment]
我刚打完这行字就能用了 好奇怪

**Comment by saltpi** [comment]
触控板是可以通过键盘关闭打开的，详细见readme里面changelog

**Comment by dakkidaze** [comment]
不是因为关掉的原因（安装完成后试过），但是具体原因不清楚

**Comment by saltpi** [comment]
安装完后清理下驱动缓存就行了

**Comment by dakkidaze** [comment]
现在基本完美了，谢谢您付出的精力和时间

**Comment by aone520** [comment]
楼主，亮度调节的有更新吗，就差亮度调节了

**Comment by saltpi** [comment]
@aone520 亮度调节没有问题，你得外接个键盘或者鼠标在`  偏好设置 `键盘里面设置一下亮度调节的快捷键

**Comment by aone520** [comment]
哦哦，我试试，笔记本的亮度调节按钮也可以设置吗

**Comment by saltpi** [comment]
@aone520 可以

**Comment by aone520** [comment]
楼主，现在电脑插耳机有一直嗡嗡的声音，一直有，需要设置什么

**Comment by saltpi** [comment]
@aone520 
![Screenshot_2019-05-31-12-25-09-197_com android chrome](https://user-images.githubusercontent.com/33711476/58681506-40b2a900-839f-11e9-968c-f91465e6c449.png)

执行耳麦和内置麦克风切换脚本

**Comment by aone520** [comment]
我下载的最新的efi，哪里还需要改吗

**Comment by saltpi** [comment]
@aone520 用我上面的哪个efi里面的` alc_fix `安装守护程序

**Comment by aone520** [comment]
好的

**Comment by aone520** [comment]
![DFD61218-7C0B-4A1E-8DB4-F5CF6BEEAE84](https://user-images.githubusercontent.com/45387125/59960036-45790180-94f4-11e9-9f73-bdce537ef2d6.jpeg)
![7ECCFC23-E1EF-4D8F-86B5-789C60EDC163](https://user-images.githubusercontent.com/45387125/59960037-45790180-94f4-11e9-81ec-39f42dd90bec.jpeg)
用黑果小兵安装的，第二步也到安装界面了，安装完成后，重启就报这个了，以前安全可以正常重启到设置页面的

**Comment by saltpi** [comment]
@aone520 先用镜像里面的efi安装，安装成功以后再换成我的

**Comment by aone520** [comment]
上个月成功了，昨天命令输错了，把盘请清了，重新安装的，就是用原来镜像的安装的，引导也是镜像的。装完重启就提示这个了，还没有换你的efi呢，难道原版装成功后会锁定主板么

**Comment by saltpi** [comment]
@aone520 你可以试着使用我的efi，但是不使用我的config.plist,用黑果小兵的config.plist.毕竟你这可能是某个驱动导致的内核恐慌
