### ISSUE TITLE
可以分享一下 dsdt 的制作过程吗

### ISSUE THREAD

**Issue by YiqinZhao** [ourfor/Mibook-air#11]
非常感谢！

**Comment by saltpi** [comment]
- 如果是完全自己写的话就得熟悉[ACPI](https://www.acpica.org/documentation)，但是一般我们都是根据Rehabman的[教程](https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/)提取机器的dsdt和ssdt，然后反编译，然后通过大神补丁源打补丁

- 不够随着Hackintool的发布，可以直接生成补丁，这个软件的使用教程可以见[黑果小兵的博客](https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html)

**Comment by YiqinZhao** [comment]
非常感谢🙏
