### ISSUE TITLE
5月29号的Release能和黑果小兵的10.14.5镜像一起用吗

### ISSUE THREAD

**Issue by cwt8805** [ourfor/Mibook-air#15]

**Comment by saltpi** [comment]
可以，但是安装的时候得用` config_install.plist `,不能用原来的配置文件,[config_install.plist](https://github.com/ourfor/Mibook-air/blob/master/EFI/CLOVER/config_install.plist)

**Comment by cwt8805** [comment]
用你仓库里面的这个config_install.plist替换U盘esp分区里的config_install.plist再安装，是这样吗

**Comment by saltpi** [comment]
对，改名为` config.plist `
