### ISSUE TITLE
如何更新macOS系统

### ISSUE THREAD

**Issue by iotguard** [ourfor/Mibook-air#16]
我想从10.4.4更新到10.4.6，在软件更新中下载更新并重启后选择启动项boot macOS install from macos后更新失败，然而选择boot macOS from macos还是可以进入原来系统的。

**Comment by iotguard** [comment]
是用的5月29号最新的EFI

**Comment by saltpi** [comment]
现在可以用10.14.5，10.14.6还没测试，打算到时候直接上`catalina`

**Comment by iotguard** [comment]
好的，谢谢，那如何删除这个更新和Clover中的启动项

**Comment by saltpi** [comment]
在`Finder`里面打开系统所在盘符，文件夹叫什么名不记得了，但是你应该能知道删那个文件夹
这是比较正常的目录结构
![image](https://user-images.githubusercontent.com/33711476/62818144-85b04400-bb75-11e9-9e25-c13c17c65b86.png)

**Comment by iotguard** [comment]
搞定了，多谢
