### ISSUE TITLE
10.14.4系统偏好设置和系统信息都没有蓝牙

### ISSUE THREAD

**Issue by jonahyang0106** [ourfor/Mibook-air#18]
因为刚刚有消息说板载蓝牙可以驱动了，想试一试但是发现系统偏好设置里和系统信息里都没有蓝牙，想问一下怎么解除蓝牙的屏蔽。
下面附板载蓝牙驱动的地址：https://www.bilibili.com/video/av81701937

**Comment by saltpi** [comment]
到时候我看看，intel蓝牙是可以用的，但是有些机型用不了的，我们的就属于这种

**Comment by jonahyang0106** [comment]
感谢大佬回复！之前看到群里有人说米pro和air驱动成功了，但是我这里一直没有蓝牙的选项，替换成黑果小兵的镜像自带efi后出现了，所以想来问问大佬有没有什么解决方法

**Comment by saltpi** [comment]
你把
![image](https://user-images.githubusercontent.com/33711476/71657184-c5bcd100-2d79-11ea-851f-d105a6445278.png)
这两个删了就行，看看能不能驱动喽

**Comment by jonahyang0106** [comment]
试了一下只装Intelbluetoothfirmware.kext可以出现蓝牙选项和图标，但是依旧没有办法驱动，这里给大佬贴一下源代码网址：https://github.com/zxystd/IntelBluetoothFirmware

**Comment by saltpi** [comment]
等下试试

**Comment by saltpi** [comment]
源码编译了一下，不行，和以前一样地址还是 `00-00-00-00-00-00`

**Comment by jonahyang0106** [comment]
问了一下原作者，这个驱动是用10.15的sdk编译的，我是10.14所以需要用更低版本的sdk编译

**Comment by saltpi** [comment]
我是自己编译的

**Comment by jonahyang0106** [comment]
我之前也自己编译了一遍也是不行，看了一下我的sdk也是10.15的，现在在满世界找10.14的sdk包:(

**Comment by saltpi** [comment]
编译选项里面我设置的是10.14

**Comment by jonahyang0106** [comment]
我自己编译了一遍也不行，我试试升级一下macOS吧，感谢大佬回复！

**Comment by saltpi** [comment]
升级了一下macOS, 蓝牙确实可以使用

**Comment by saltpi** [comment]
![截屏2020-01-15上午12 18 06](https://user-images.githubusercontent.com/33711476/72422555-a84a2700-37bd-11ea-8e79-7eb7e777590c.png)

还有些配置没弄好，有能力可以自行升级

**Comment by jonahyang0106** [comment]
谢谢大佬，再有就是请问从14.4升到15需要做的工作有哪些？是更换efi文件夹再更新就好了吗？因为我上次尝试更新的时候出现了白色感叹号

**Comment by saltpi** [comment]
目前在测试OC引导，Clover引导，我现在更新下

**Comment by saltpi** [comment]
目前使用的系统是
![image](https://user-images.githubusercontent.com/33711476/74124465-63bf7900-4c0d-11ea-8684-11861ed14da3.png)
可以正常通过系统偏好设置更新
- 关于测试的WiFi驱动，可以正常联网，当时非常不稳定，会重启，具体见[Intel WiFi驱动成功](http://bbs.pcbeta.com/viewthread-1838489-1-1.html)
- 关于蓝牙
![image](https://user-images.githubusercontent.com/33711476/74124432-4b4f5e80-4c0d-11ea-91a9-e7a0db6267ff.png)
无线鼠标目前无法正常使用, 期待作者修复
其它设备如: 蓝牙耳机工作正常

**Comment by jonahyang0106** [comment]
直接通过系统偏好设置更新吗？在此之前需要做其他的工作吗？

**Comment by saltpi** [comment]
可以直接通过系统更新


 
---原始邮件---
发件人: "jonahyang0106"<notifications@github.com&gt;
发送时间: 2020年2月10日 14:34:36
收件人: "ourfor/Mibook-air"<Mibook-air@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Sagit"<2320813747@qq.com&gt;;
主题: Re: [ourfor/Mibook-air] 10.14.4系统偏好设置和系统信息都没有蓝牙 (#18)



直接通过系统偏好设置更新吗？在此之前需要做其他的工作吗？

**Comment by jonahyang0106** [comment]
好的，请问efi是使用刚刚更新的master分支里的文件进行替换嘛？

**Comment by saltpi** [comment]
是的，我拷贝我现在用的efi上传上去的，我这15.3是有的，清理下缓存试试？


 
---原始邮件---
发件人: "jonahyang0106"<notifications@github.com&gt;
发送时间: 2020年2月10日 14:41:24
收件人: "ourfor/Mibook-air"<Mibook-air@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Sagit"<2320813747@qq.com&gt;;
主题: Re: [ourfor/Mibook-air] 10.14.4系统偏好设置和系统信息都没有蓝牙 (#18)



好的，请问efi是使用刚刚更新的master分支里的文件进行替换嘛？

**Comment by jonahyang0106** [comment]
我在更新的过程中，重启第一次后发生了无限重启的情况，请问大佬又遇到过吗

**Comment by jonahyang0106** [comment]
我在想是不是我没有更新clover的缘故

**Comment by saltpi** [comment]
没有，你等待了多长时间？10分钟以内的样子应该会继续安装吧


 
---原始邮件---
发件人: "jonahyang0106"<notifications@github.com&gt;
发送时间: 2020年2月10日 15:56:55
收件人: "ourfor/Mibook-air"<Mibook-air@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Sagit"<2320813747@qq.com&gt;;
主题: Re: [ourfor/Mibook-air] 10.14.4系统偏好设置和系统信息都没有蓝牙 (#18)



我在更新的过程中，重启第一次后发生了无限重启的情况，请问大佬又遇到过吗

**Comment by jonahyang0106** [comment]
是在白苹果读条界面直接自动关机重启，再进入install后显示遇到问题重启了，然后会重复以上情况

**Comment by jonahyang0106** [comment]
是panic了

**Comment by saltpi** [comment]
要更新


 
---原始邮件---
发件人: "jonahyang0106"<notifications@github.com&gt;
发送时间: 2020年2月10日 15:58:41
收件人: "ourfor/Mibook-air"<Mibook-air@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Sagit"<2320813747@qq.com&gt;;
主题: Re: [ourfor/Mibook-air] 10.14.4系统偏好设置和系统信息都没有蓝牙 (#18)



我在想是不是我没有更新clover的缘故

**Comment by saltpi** [comment]
我刚才试了下，确实有问题，应该是git提交的问题，我重新上传了，你再试试，再不然我再给你发压缩文件

**Comment by jonahyang0106** [comment]
嗯嗯，我刚刚试了一下更新clover，刚才的Panic已经过关了，目前正在安装，感谢大佬一路指导

**Comment by jonahyang0106** [comment]
![截屏2020-02-10下午7 35 16](https://user-images.githubusercontent.com/59429824/74146640-83ba6100-4c3c-11ea-8e7a-d36aff375d52.png)
小问题就是板载网卡好像无法驱动，所以App Store和iMessage好像用不了，我尝试了kextutility重建缓存还是不行，请问您有遇到这种情况吗
