### ISSUE TITLE
Migrate to OC

### ISSUE THREAD

**Issue by johnnynunez** [ourfor/Mibook-air#19]
I post it some examples..
https://github.com/daliansky/XiaoMi-Pro-Hackintosh
https://github.com/johnnync13/Xiaomi-Mi-Air
https://github.com/johnnync13/EFI-Xiaomi-Notebook-air-12-5
https://github.com/johnnync13/Xiaomi-Notebook-Air-1Gen

**Comment by saltpi** [comment]
in `oc` branch :D

**Comment by johnnynunez** [comment]
@ourfor in oc with the tutorial:  http://bbs.pcbeta.com/viewthread-1839143-1-1.html
Does your trackpad work? We have the same bios, and the same DSDT,SSDT and trackpad driver
The open core documentation say that SSDT-XOSI should be removed

**Comment by saltpi** [comment]
trackpad work well(***GPIO mode***)
![image](https://user-images.githubusercontent.com/33711476/79068197-b5f94500-7cf7-11ea-9aae-cf3a9b6ec27c.png)
I use `SSDT-XOSI` to enable `VoodooI2C-Patches`

**Comment by johnnynunez** [comment]
@ourfor with the latest version of voodooi2c is not required SSDT-XOSI, like my other projects or Xiaomi Pro project examples. The problem to use XOSI with OpenCore is the dual boot not works, like windows or linux

**Comment by saltpi** [comment]
OK, I will remove it late and upgrade voodooi2c 👍

**Comment by johnnynunez** [comment]
@ourfor Now the voodooi2c requires voodooInput to enable mt2 engine. It is on voodoops2 project in folder plugins like voodoops2keyboard
