### ISSUE TITLE
待机有时声音会消失（能调音量，但是没有声音）有时睡眠会无法唤醒屏幕

### ISSUE THREAD

**Issue by FrostMiKu** [ourfor/Mibook-air#2]
使用的master分支的EFI
10.13.4
（重启后会恢复正常

**Comment by saltpi** [comment]
这个可以刷BIOS解决睡眠唤醒问题，因为这个dsdt是我根据我的BIOS版本打的，readme里面有提到，
我笔记本BIOS的版本是'` 0705 `，如果你使用这个EFI后遇到笔记本无法休眠，即无故睡死，可以通过dsdt打补丁，也可以刷和我版本相同的BIOS,相关[教程](http://bbs.xiaomi.cn/t-13643021) ,解决睡眠无声驱动已经更新

**Comment by FrostMiKu** [comment]
谢谢
