### ISSUE TITLE
据说 intel 网卡可以驱动了，不知在我们机型上是否可用

### ISSUE THREAD

**Issue by billhhh** [ourfor/Mibook-air#22]
rt

**Comment by saltpi** [comment]
已经用上了


 
---原始邮件---
发件人: "Bill Wang"<notifications@github.com&gt;
发送时间: 2020年6月16日 11:47:37
收件人: "ourfor/Mibook-air"<Mibook-air@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ourfor/Mibook-air] 据说 intel 网卡可以驱动了，不知在我们机型上是否可用 (#22)




 
rt

**Comment by billhhh** [comment]
是不是在下一版本 release 中发布 =)

**Comment by saltpi** [comment]
可以看看这个 [教程](http://bbs.pcbeta.com/viewthread-1848662-1-1.html)
Release不会考虑，毕竟这个解决方案并不是很完美。
