### ISSUE TITLE
外接显示器无法分屏

### ISSUE THREAD

**Issue by ghost** [ourfor/Mibook-air#4]
我是外接显示器无法分屏
版本是10.13.6 (17G2112)

**Comment by ghost** [comment]
外接显示器后没有任何反应， 显示设置哪里也没有关于多屏的设置

**Comment by saltpi** [comment]
是否打开hidpi？

**Comment by saltpi** [comment]
要关闭hidpi才能调出多屏设置

**Comment by ghost** [comment]
关闭hidpi后还是没有多屏设置

发自我的 iPhone

**Comment by saltpi** [comment]
你试试最新的efi

**Comment by ghost** [comment]
还是不行，估计是系统版本不对吧

by zoain
