### ISSUE TITLE
睡眠后还是会出现声音丢失

### ISSUE THREAD

**Issue by zoain-it** [ourfor/Mibook-air#5]
mac10.14.1 睡眠后声音消失，最新版efi

**Comment by saltpi** [comment]
> mac10.14.1 睡眠后声音消失，最新版efi

这个有时间再搞吧，最近有点忙

**Comment by zoain-it** [comment]
嗯嗯

**Comment by saltpi** [comment]
- 确保`/ESP/EFI/CLOVER/kexts/Other/  `目录下有驱动 ***CodecCommander.kext***
- 下载[hda-verb](https://github.com/ourfor/Mibook-air/raw/master/EFI/CLOVER/kexts/Other/hda-verb),将该文件放到` /usr/bin `目录下。
- 清除驱动缓存,重启

**Comment by zoain-it** [comment]
好的谢谢
