### ISSUE TITLE
有时候触摸板会变成3指右键

### ISSUE THREAD

**Issue by FrostMiKu** [ourfor/Mibook-air#6]
双击选中（拖动窗口，图标）无效，感觉比较影响无鼠标时的正常使用。
最新efi，
10.14系统。

另外大佬现在在用10.13还是10.14啊😯

**Comment by saltpi** [comment]
- 10.14
- ` 系统偏好设置 ` -> ` 辅助功能 ` -> ` 鼠标和触控板 ` -> ` 触控板选项 ` -> ` 启用拖动 `

**Comment by saltpi** [comment]
- 单指双击同时移动手指实现拖动图标

**Comment by FrostMiKu** [comment]
哦哦，谢谢 dalao ，另外我发现有时候触摸板会变成3指右键，我搜到了一个[解决方案](http://bbs.pcbeta.com/viewthread-1763607-1-1.html)

**Comment by saltpi** [comment]
这个感觉没必要吧😂，之前就是两指查询数据，有网友反馈说不太像MacOS.😅

**Comment by FrostMiKu** [comment]
😂为什么我pull下来的两指右键休眠唤醒后会变成两指查询。按照上面改了就好了😂
另外我的📅不知道为什么不能从iCloud同步

**Comment by FrostMiKu** [comment]
📅通过网页解决了
