### ISSUE TITLE
没有内建虚拟网卡么

### ISSUE THREAD

**Issue by FrostMiKu** [ourfor/Mibook-air#7]
用最新的release重装了一遍现在app store登陆不了啦= =|||

**Comment by saltpi** [comment]
我很久以前遇到过这问题，调整下网卡的顺序，试试下面的解决方法:
- 删除 ` /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist `
- 在` 系统设置偏好／网络 ` 里删除所有网络连接
- 重新启动
- 重新在` 系统设置偏好／网络 ` 加网络连接

**Comment by FrostMiKu** [comment]
- 还是不行，输入错误的密码会提示密码不正确，输入正确的密码后
![image](https://user-images.githubusercontent.com/8232546/52725826-e575ca00-2fec-11e9-96f0-501288dec674.png)
登录框会消失但还处于未登录状态。猜想会不会和序列号有关系？

- 系统偏好/网络 里没有“以太网”这个选项

**Comment by FrostMiKu** [comment]
另外硬件信息里也没有网卡
![image](https://user-images.githubusercontent.com/8232546/52726145-8e242980-2fed-11e9-8ad9-3b3aa0ee4e62.png)

**Comment by saltpi** [comment]
- 你用的是有线网卡吗？有线网卡驱动我已经移除了。

**Comment by FrostMiKu** [comment]
我用的是USB无线网卡，能上网就是登陆不了app store，iCloud正常

**Comment by saltpi** [comment]
- 无线网卡的信息是在USB里面查看的，以太网是需要用有线网卡拨号的。
- 建议按照按照上面的步骤移除网络后，可以重装一下USBwifi驱动.
- 感觉和这个序列号好像关系不是很大，序列号我都没啥用.
<img width="780" alt="2019-02-14 10 44 07" src="https://user-images.githubusercontent.com/33711476/52759056-87290580-3045-11e9-83a7-c7b28d90b131.png">
<img width="863" alt="2019-02-14 10 45 12" src="https://user-images.githubusercontent.com/33711476/52759084-a031b680-3045-11e9-94aa-a8cc61f979db.png">

**Comment by FrostMiKu** [comment]
这么操作了一遍还是不行
![image](https://user-images.githubusercontent.com/8232546/52760851-0d484a80-304c-11e9-863e-2a1685f8a905.png)
难道是我这个usb无线网卡的问题= =？

**Comment by FrostMiKu** [comment]
- en0 是 usb 无线网卡
- en1 是Android USB 网络共享

**Comment by saltpi** [comment]
这个我不是很清楚了，毕竟没怎么遇到过。😅

**Comment by FrostMiKu** [comment]
现在睡眠唤醒还是会丢失声音啊0.0

**Comment by saltpi** [comment]
- 睡眠唤醒的ssdt我做好了，还没有更新上来，还有这个usb内建的ssdt也做好了，我把USB hub放在学校了，所以这type-c接口还没完全弄好，等开学测试好了，就会更上去。

**Comment by saltpi** [comment]
丢失声音手动恢复:
- ` sudo kextunload /System/Library/Extensions/AppleHDA.kext `
- ` sudo kextload /System/Library/Extensions/AppleHDA.kext `

**Comment by FrostMiKu** [comment]
重装系统折腾了一晚上还不行，后来看到了这个新闻
![image](https://user-images.githubusercontent.com/8232546/52836815-2b36ad80-3127-11e9-8119-58bb9ee48982.png)

**Comment by saltpi** [comment]
😳😂😂
